/**
 * generated by Xtext
 */
package org.muml.uppaal.validation;

import org.muml.uppaal.validation.AbstractUppaalXMLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class UppaalXMLValidator extends AbstractUppaalXMLValidator {
}
